services:
  efa:
    container_name: efacloud-app
    build:
      context: .
    #volumes:
      #- ./efa-config:/var/www/html/config
      #- ./efa:/var/www/html
    ports:
      - 8080:80
    #depends_on:
    #  - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: efacloud-db
    #volumes:
    #  - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=efaCloud
      - MYSQL_USER=test
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}


# $ docker-compuse up --build
# http://localhost:8080/install.php

# https://www.efacloud.org/src/
# https://hub.docker.com/_/php
